name: Benchmark

on:
  workflow_dispatch: {}
  push: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-with-depot:
    name: Build with Depot
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout
        with:
          submodules: recursive

      - uses: depot/setup-action@v1

      - name: Build and tag image
        uses: depot/build-push-action@v1
        with:
          context: ./upstream/backend/
          platforms: linux/amd64,linux/arm64
          project: qs6t70m51x
