name: Benchmark

on:
  workflow_dispatch: {}
  push: {}

jobs:
  build-with-depot:
    name: Build image with Depot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout
        with:
          submodules: recursive

      - uses: depot/setup-action@v1

      - name: Build and tag image
        uses: depot/build-push-action@v1
        with:
          context: ./upstream/backend/
          platforms: linux/amd64,linux/arm64
